# https://taskfile.dev

version: '3'

tasks:
  default:
    cmd: task --list

  build:
    desc: Build the application
    cmds:
      - cmd: go build -o ./bin/buildforthechurch-build cmd/agentbuild/main.go
        platforms: [darwin, linux]
      - cmd: go build -o ./bin/buildforthechurch-api cmd/api/main.go
        platforms: [darwin, linux]
      - cmd: go build -o ./bin/buildforthechurch-build.exe cmd/agentbuild/main.go
        platforms: [windows]
      - cmd: go build -o ./bin/buildforthechurch-api.exe cmd/api/main.go
        platforms: [windows]
      

  run:
    desc: Run the application
    cmd: go run cmd/agentbuild/main.go

  clean:
    desc: Clean up the build artifacts
    cmd: rm -f ./bin/buildforthechurch

  api:
    desc: Run the API
    cmd: go run cmd/api/main.go