name: Empty Commit on Main Push (Needed to deploy to Vercel)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch last 2 commits to check the author

      - name: Check if last commit was made by me
        id: check-author
        run: |
          LAST_COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
          MY_EMAIL="${{ secrets.GIT_AUTHOR_EMAIL }}"

          if [ "$LAST_COMMIT_EMAIL" = "$MY_EMAIL" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Skipping because last commit was made by vercel team member"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "Proceeding because last commit was made by someone not on vercel team"
          fi

      - name: Set up Git user
        if: steps.check-author.outputs.skip == 'false'
        run: |
          git config --global user.name "${{ secrets.GIT_AUTHOR_NAME }}"
          git config --global user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"

      - name: Create empty commit and push
        if: steps.check-author.outputs.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          git commit --allow-empty -m "chore: trigger vercel deploy [skip ci]"
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
