name: Empty Commit on Main Push (Needed to deploy to Vercel)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch last 2 commits to check the author

      - name: Get last commit author and check collaborator status
        id: check-author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the last commit SHA
          LAST_COMMIT_SHA=$(git log -1 --pretty=format:'%H')
          echo "Last commit SHA: $LAST_COMMIT_SHA"
          
          # Get commit details from GitHub API to extract the author's username
          HTTP_CODE=$(curl -s -w "%{http_code}" -o /tmp/commit_response.json \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits/$LAST_COMMIT_SHA")
          
          # Check if the API call was successful
          if [ "$HTTP_CODE" != "200" ]; then
            echo "Failed to fetch commit data (HTTP $HTTP_CODE). Proceeding with empty commit."
            echo "skip=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Extract the author's username from the API response
          if ! LAST_COMMIT_USERNAME=$(jq -r '.author.login // empty' /tmp/commit_response.json 2>/dev/null); then
            echo "Failed to parse commit data. Proceeding with empty commit."
            echo "skip=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          if [ -z "$LAST_COMMIT_USERNAME" ] || [ "$LAST_COMMIT_USERNAME" = "null" ]; then
            echo "Could not determine GitHub username from commit. Proceeding with empty commit."
            echo "skip=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "Last commit author username: $LAST_COMMIT_USERNAME"
          
          # Check if the user is a collaborator using GitHub API
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators/$LAST_COMMIT_USERNAME")
          
          echo "API response status: $HTTP_STATUS"
          
          # Check for successful collaborator check (204) or handle errors
          if [ "$HTTP_STATUS" = "204" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Skipping because last commit author is a collaborator"
          elif [ "$HTTP_STATUS" = "404" ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "Proceeding because last commit author is not a collaborator"
          else
            echo "Unexpected API response ($HTTP_STATUS). Proceeding with empty commit."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Git user
        if: steps.check-author.outputs.skip == 'false'
        run: |
          git config --global user.name "${{ secrets.GIT_AUTHOR_NAME }}"
          git config --global user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"

      - name: Create empty commit and push
        if: steps.check-author.outputs.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit --allow-empty -m "chore: trigger vercel deploy [skip ci]"
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
